### ISSUE TITLE
Integrate Netlify CMS within main site

### ISSUE THREAD

**Issue by WhiteHoodHacker** [sigpwny/websites#125]
Doing so would allow us to use our custom React components for better previews when editing content.

Will require some hackery with the Netlify site where the Netlify Identity is enabled (cms.sigpwny.com) to allow the base site sigpwny.com hosted on Cloudflare Pages to interact with Netlify Identity (and git gateway). CORS will be an issue since the Netlify site returns:
```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
```
The fix would be to set a `_headers` file on the Netlify site with `Access-Control-Allow-Origin: https://sigpwny.com`.

The Netlify CMS `config.yml` probably needs to be updated to include the `site_domain: cms.sigpwny.com` field for the backend option. Reference: https://preview-auth-doc--netlify-cms-www.netlify.app/docs/authentication-backends/#options

**Comment by reteps** [comment]
Closed by #247
