### ISSUE TITLE
PDF.js increases bundle size significantly

### ISSUE THREAD

**Issue by WhiteHoodHacker** [sigpwny/websites#176]
PDF.js increases bundle size significantly (25% of JS bundle) and is rarely used (usually, the YouTube video iframe will replace the slide viewer). We should either look into alternative options or do some code splitting.

**Comment by reteps** [comment]
i vote to remove the PDF viewer in this case.

**Comment by WhiteHoodHacker** [comment]
Yes, I replaced it with a simple iframe in the Astro branch.
